name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Checkout daps2docker repo
      uses: actions/checkout@v5
      with:
        repository: openSUSE/daps2docker
        path: daps2docker
    - name: Build
      run: |
        pushd daps2docker
        ./daps2docker.sh ../DC-obs-all html || exit 1
    - name: Upload artifacts for inspection
      uses: actions/upload-artifact@v5
      with:
        name: obs-docu-html
        path: /tmp/daps2docker-*/obs-all/html/obs-all/
